ALTER TABLE orders
    ADD COLUMN mode VARCHAR(16) NOT NULL DEFAULT 'TIME',
  ADD COLUMN total_drinks INT NOT NULL DEFAULT 0;


ALTER TABLE orders
    ALTER COLUMN guests DROP NOT NULL,
ALTER COLUMN drinks_per_person DROP NOT NULL,
  ALTER COLUMN duration_hours DROP NOT NULL;
